swagger: "2.0"
info:
  title: "Daily Memo API Memo Responses Define"
  description: |
    20200517 - First Initialize
  version: "1.0.0"
paths: {}
responses:
  ResGetMemoList:
    description: Memo 리스트 조회 응답
    schema:
      allOf:
      - $ref: "../models/daily-memo-rest-api-models.yaml#/definitions/ResponseBase"
      - type: object
        properties:
            body:
              type: object
              properties:
                contents:
                  type: array
                  items:
                    $ref: "../models/daily-memo-rest-api-memo-models.yaml#/definitions/BaseMemo"
  ResCreateMemo:
    description: Memo 생성 응답
    schema:
      $ref: "../models/daily-memo-rest-api-models.yaml#/definitions/ResponseBase"
  ResPatchMemo:
    description: Memo 업데이트 응답
    schema:
      $ref: "../models/daily-memo-rest-api-models.yaml#/definitions/ResponseBase"
  ResDeleteMemo:
    description: Memo 삭제 응답
    schema:
      $ref: "../models/daily-memo-rest-api-models.yaml#/definitions/ResponseBase"
  
          