swagger: "2.0"
info:
  title: "Daily Memo API Docs"
  description: |
    20200514 - First Initialize
  version: "1.0.0"
host: "locahost:3625"
basePath: "/api/v1.0"
securityDefinitions:
  ApiKey:
    type: apiKey
    in: header
    name: x-api-key
  TokenKey:
    type: apiKey
    in: header
    name: x-api-token
tags:
  - name: "Login"
    description: "로그인"
  - name: "User"
    description: "사용자 관리"
  - name: "Memo"
    description: "Memo 관리"
  - name: "Group"
    description: "Memo Group 관리"
  - name: "Tag"
    description: "Tag 관리"
schemes:
  - "https"
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /login:
    post:
      tags: [Login]
      summary: "User Athentication"
      description: "사용자 인증"
      security:
        - ApiKey: []
      parameters:
        - $ref: "./parameters/daily-memo-rest-api-parameters.yaml#/parameters/Login"
      responses: 
        default:
          $ref: "./responses/daily-memo-rest-api-responses.yaml#/responses/ResLoginSuccess"
  /user:
    get:
      tags: [User]
      summary: "Get User List"
      description: "사용자 리스트 조회"
      security:
        - ApiKey: []
        - TokenKey: []
      responses:
        default:
          $ref: "./responses/daily-memo-rest-api-user-responses.yaml#/responses/ResGetUserList"
    post:
      tags: [User]
      summary: "Create User Info"
      description: "사용자 정보 생성"
      security:
        - ApiKey: []
        - TokenKey: []
      parameters:
        - $ref: "./parameters/daily-memo-rest-api-user-parameters.yaml#/parameters/ParamCreateUser"
      responses:
        default:
          $ref: "./responses/daily-memo-rest-api-user-responses.yaml#/responses/ResCreateUser"    
  /memo:
    get:
      tags: [Memo]
      summary: "Get Memo List"
      description: "메모 리스트 조회"
      security:
        - ApiKey: []
        - TokenKey: []
      parameters:
        - $ref: "./parameters/daily-memo-rest-api-memo-parameters.yaml#/parameters/ParamGetMemoList"
      responses:
        default:
          $ref: "./responses/daily-memo-rest-api-memo-responses.yaml#/responses/ResGetMemoList"  
    post:
      tags: [Memo]
      summary: "Create Memo"
      description: "신규 메모 생성"
      security:
        - ApiKey: []
        - TokenKey: []
      parameters:
        - $ref: "./parameters/daily-memo-rest-api-memo-parameters.yaml#/parameters/ParamCreateMemo"
      responses:
        default:
          $ref: "./responses/daily-memo-rest-api-memo-responses.yaml#/responses/ResCreateMemo"
    patch:
      tags: [Memo]
      summary: "Patch Memo"
      description: "메모 업데이트"
      security:
        - ApiKey: []
        - TokenKey: []
      parameters:
        - $ref: "./parameters/daily-memo-rest-api-memo-parameters.yaml#/parameters/ParamPatchMemo"
      responses:
        default: 
          $ref: "./responses/daily-memo-rest-api-memo-responses.yaml#/responses/ResPatchMemo"
    delete:
      tags: [Memo]
      summary: "Delete Memo"
      description: "메모 삭제"
      security:
        - ApiKey: []
        - TokenKey: []
      parameters:
        - $ref: "./parameters/daily-memo-rest-api-memo-parameters.yaml#/parameters/ParamDeleteMemo"
      responses:
        default:
          $ref: "./responses/daily-memo-rest-api-memo-responses.yaml#/responses/ResDeleteMemo"
